weather:
  api:
    key:  a7337a15a15764b5814e0ecf172a1f61
    units:  metric
    language: ru
  city:
    latitude:  54.864703
    longitude:  55.744475
quarkus:
#  datasource:
#    db-kind:  postgresql
#    username: user
#    password: pass
#  hibernate-orm:
#    database:
#      generation: drop-and-create
#  log:
#    category:
#      "org.jboss.resteasy.reactive.client.logging":
#        level:  DEBUG
  rest-client:
    read-timeout: 90000
#    logging:
#      scope:  request-response
#      body-limit: 1024
    weather-api:
#      verify-host:  false
      scope:  jakarta.inject.Singleton
    "ru.km.weather.client.ForecastClient":
      url:  https://api.openweathermap.org/data/2.5
