weather:
  api:
    key: xxx
    units: metric
    language: ru
  city:
    latitude: 54.867
    longitude: 55.750
#https://www.openstreetmap.org/#map=19/54.864679/55.744092
quarkus:
#  swagger-ui:
#    always-include: true
  http:
    port: 8080
  datasource:
    db-kind: postgresql
    username: user
    password: pass
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script:  scripts/load-data.sql
#    log:
#      category:
#        "org.jboss.resteasy.reactive.client.logging":
#          level:  DEBUG
  rest-client:
    read-timeout: 90000
    logging:
      scope: request-response
      body-limit: 1024
    weather-api:
      #      verify-host:  false
      scope: jakarta.inject.Singleton
    "ru.km.weather.collector.rest.OpenWeatherMapClient":
      url: https://api.openweathermap.org/data/2.5